#path to executable file (do not specify "./" in the beginning of the filename if executable file in same directory)
exiftool: "exiftool"

extensions: ["jpg","jpeg","png","bmp"]

#fields to be fetched from image files
fields: ["exif","iptc","xmp","icc_profile"]