#path to a folder with executable file (omit "./" in the beginning of the path), relate to executable file
exiftool: "exiftool"

#supported file extensions
extensions: ["jpg","jpeg","png","bmp"]

#fields to be fetched from image files and used for preparing a CSV output file for "scan" command
fields: ["exif","iptc","xmp","icc_profile"]