#path to executable file (avoid using "./" in the beginning of the filename)
exiftool: "exiftool"

#fields to be fetched from image files
fields: ["exif", "iptc", "xmp", "icc_profile"]

#known tags aliases
tagmap:
  title: ["IPTC:Headline", "XMP:Headline"]
  keywords: ["IPTC:Keywords", "XMP:Subject"]
  event: ["XMP:Event"]
  dateCreated: ["IPTC:DateCreated", "XMP:DateCreated"]
  copyright: ["EXIF:Copyright", "IPTC:CopyrightNotice", "XMP:Rights"]
  description: ["EXIF:ImageDescription", "IPTC:Caption-Abstract", "XMP:Description"]
  personInImage: ["XMP:PersonInImage"]
  transmission: ["IPTC:OriginalTransmissionReference", "XMP:TransmissionReference"]
  country: ["IPTC:Country-PrimaryLocationName", "XMP:Country"]
  countryCode: ["IPTC:Country-PrimaryLocationCode", "XMP:CountryCode"]
  state: ["IPTC:Province-State", "XMP:State"]
  city: ["IPTC:City", "XMP:City"]
  location: ["IPTC:Sub-location", "XMP:Location"]
  instructions: ["IPTC:SpecialInstructions", "XMP:Instructions"]
  terms: ["XMP:UsageTerms"]
  creator: ["EXIF:Artist", "IPTC:By-line", "XMP:Creator"]
  creatorTitle: ["IPTC:By-lineTitle", "XMP:AuthorsPosition"]
  creatorAddress: ["XMP:CreatorAddress"]
  creatorCity: ["XMP:CreatorCity"]
  creatorRegion: ["XMP:CreatorRegion"]
  creatorPostalcode: ["XMP:CreatorPostalCode"]
  creatorCountry: ["XMP:CreatorCountry"]
  creatorWorkTelephone: ["XMP:CreatorWorkTelephone"]
  creatorWorkEmail: ["XMP:CreatorWorkEmail"]
  creatorWorkURL: ["XMP:CreatorWorkURL"]
  credit: ["IPTC:Credit", "XMP:Credit"]
  source: ["IPTC:Source", "XMP:Source"]
